### PR TITLE
Typescript definition improvements

### PR DESCRIPTION
**Pull request by darcyparker**
This iterates on the work accepted here: https://github.com/Esri/Terraformer/issues/296

* Updated tslint rules so there are no code style issues in `index.d.ts`
* Added missing `npm @types` required to satisfy the intellisense-like features tsc provides to your favourite editor.
* And most importantly, added the Terraformer namespace back.  This was necessary for: https://github.com/darcyparker/terraformer-wkt-parser/tree/typescriptDefinitionFixes (which will be a pending pull request.)

### CODE REVIEW

**Comment by darcyparker** [comment]
https://github.com/Esri/terraformer-wkt-parser/pull/28 is drafted pull request to demonatrate need to bring `Terraformer` namespace back.

**Comment by jgravois** [comment]
thanks for the contribution @darcyparker! 

curious to hear @JeffJacobson's take when he can spare the time.

**Comment by darcyparker** [comment]
I should also point out... There was a question/discussion https://github.com/Esri/Terraformer/issues/296#issuecomment-284569936 about `export = Terraformer;`.  I added this back in and put a reason in comment. The namespace needs to be exported twice. Once for ES6 and once for AMD. Subtle... I learned about this from other project's `.d.ts`.

**Comment by JeffJacobson** [comment]
@jgravois As long as the changes don't break anything for anybody, then it should be fine.

The style I used in my most recent commit to this project is what was recommended to me when I committed type definitions to https://github.com/DefinitelyTyped/DefinitelyTyped/. The advice from Microsoft and others on the "best" way to create type definitions seems to continually change.

**Comment by darcyparker** [comment]
@JeffJacobson  - I empathize about the best practices always changing.  My motive for these changes is to get terraformer-wkt-parser.d.ts working again.  The typescript definitions broke with the last change when I did `npm install` because the semvers of the projects agreed with the dependencies.

@jgravois - If these changes break things for others, I will be motivated to help fix it quickly because I'll probably have the same issue in my work soon enough.  Thanks for reviewing this.

**Comment by jgravois** [comment]
when i `npm install && npm run test:ts`, i encounter the errors below:
```
examples/node/convert/node_modules/terraformer-arcgis-parser/node_modules/terraformer/terraformer.d.ts(39,9): error TS7010: 'forEach', which lacks return-type annotation, implicitly has an 'any' return type.
parser/node_modules/terraformer/terraformer.d.ts(128,9): error TS7010: 'steps', which lacks return-type annotation, implicitly has an 'any' return type.
examples/node/convert/node_modules/terraformer-arcgis-parser/node_modules/terraformer/terraformer.d.ts(129,9): error TS7010: 'radius', which lacks return-type annotation, implicitly has an 'any' return type.
examples/node/convert/node_modules/terraformer-arcgis-parser/node_modules/terraformer/terraformer.d.ts(130,9): error TS7010: 'center', which lacks return-type annotation, implicitly has an 'any' return type.
examples/node/convert/node_modules/terraformer-arcgis-parser/node_modules/terraformer/typings/globals/geojson/index.d.ts(18,17): error TS2300: Duplicate identifier 'Position'.
examples/node/convert/node_modules/terraformer-arcgis-parser/node_modules/terraformer/typings/globals/geojson/index.d.ts(23,22): error TS2300: Duplicate identifier 'GeometryObject'.
node_modules/@types/geojson/index.d.ts(20,17): error TS2300: Duplicate identifier 'Position'.
node_modules/@types/geojson/index.d.ts(31,17): error TS2300: Duplicate identifier 'GeometryObject'.
node_modules/@types/geojson/index.d.ts(95,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'properties' must be of type 'any', but here has type '{} | null'.
```
since all the problems seem to be isolated in /examples and /node_modules so my hunch is that they can be safely ignored and that the `tsc` command just needs tweaked, but this reminded me that it'd be a lot easier to confirm that these sorts of changes weren't inducing errors if travis executed the typescript commands when it tests each build.

**Comment by darcyparker** [comment]
@jgravois - I will have a look Monday. I think I can fix these quickly.  I was running tslint (with the project's config) via my editor with plugin and everything passed.  I neglected to test with `npm run test:ts`. 

I think you're right they can probably be ignored.  The `tsconfig.json` probably needs to be looked at.

**Comment by darcyparker** [comment]
@jgravois - I had a closer look. It wasn't the `tsconfig.json` as I first thought.

I noticed Travis was configured to use node `0.12`.  tslint and typescript 2.x require `4.2.x` and that's what I was using.  When I switched to `0.12`, I had errors like the ones you saw.  So I updated to `4.2.6` which is the latest of `4.2.x`.  I think this should resolve `npm run test:ts` issues. (It runs successfully for me.)

The open problem I am having is `grunt test`.  The `jasmine:coverage` task never finishes for me.  How long should it run? Is this a known issue?

**Comment by darcyparker** [comment]
The good thing is that Travis is passing: https://travis-ci.org/Esri/Terraformer/builds/215535498

**Comment by darcyparker** [comment]
The `tsconfig.json` correctly excludes the `node_modules` folder. By default, `tsc` should be using the `tsconfig.json` in root dir, but just to be safe, I explicitly specified to use it in the last commit.

**Comment by jgravois** [comment]
> The `jasmine:coverage` task never finishes for me. How long should it run?

on my machine, both tests execute successfully in about 3 seconds. i suspect the problem has to do with your own PhantomJS configuration, but seeing the error would help narrow it down further.

i saw a few more errors initially when i tested your changes, but they were caused by the fact that i forgot to blow away the leftover `typings/` directory with stale GeoJSON typings. whoops!

since we're going to the trouble of updating, it probably makes sense to point at [Node.js `v6`](https://nodejs.org/en/) since its in long term support, but i'm good with what you've got.

thanks for the contribution and thank you @JeffJacobson for chiming in!

**Comment by darcyparker** [comment]
Great! Thanks for merging.

**Comment by JeffJacobson** [comment]
You can have Travis CI test against [multiple versions of Node](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Specifying-Node.js-versions) if you want. Below is an example that would check against the latest version, latest 6.x version, and latest 4.x version.
```yml
language: node_js
sudo: false
before_install: npm install -g grunt-cli
node_js:
  - "node"
  - "6"
  - "4"
cache:
  directories:
  - node_modules 
```

**Comment by jgravois** [comment]
thanks for the tip, in the future it'd be sufficient to just specify `"node"`. for the time being, i can live with the bump from `0.12` to `4.x`

**Pull request merged**
