### PR TITLE
Added TypeScript definitions

### PR DESCRIPTION
**Pull request by JeffJacobson**
Added *.d.ts file for Terraformer core (terraformer.js).

### CODE REVIEW

**Comment by jgravois** [comment]
this is awesome @JeffJacobson. thx!  i'll take a deeper look and give feedback soon.

**Comment by jgravois** [comment]
forgive me for the naive questions but,

1. running `tsc` just compiles `test.ts`, correct?
2. is the purpose of `test.ts` (and derived `test.js`) to provide an example for folks who are writing their own code in TypeScript or is there more going on?
3. would folks who happen upon the project get confused that the raw source isn't actually written in TypeScript and compiled down to es5 or is this something that other projects maintain similarly?

**Comment by JeffJacobson** [comment]
1. Correct
2. The purpose is to make sure I (and subsequent developers) have written the `*.d.ts` file correctly. (You'll get compilation errors from `test.ts`)
3. Anyone who knows what a `d.ts` file is will not be confused. [These files are necessary to make TypeScript code work with JavaScript libraries that were not written in TypeScript.](http://www.typescriptlang.org/docs/handbook/writing-declaration-files.html)

**Comment by JeffJacobson** [comment]
Just making a comment to note that this pull request is related to issue #276, so that it shows up when looking at that issue.

**Comment by jgravois** [comment]
@JeffJacobson i did a little more digging and chatted a bit with @patrickarlt and since neither of us are experienced TypeScript developers, our only remaining concern relates to maintenance going forward. in submitting this PR, are you volunteering yourself to help us keep the typing files up to date in the future?  

As I'm sure you know, the project is very stable at this point, the only change i see on the horizon would be if we ever actually get the [refactor that was discussed previously](https://github.com/Esri/Terraformer/issues/268#issuecomment-196554068) off the ground.

**Pull request merged**
